name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: xu-cheng/texlive-action/full@v1
              with:
                  run: |
                      apk add git
                      apk add inkscape
                      time bash build.sh
            - name: Commit changes
              uses: EndBug/add-and-commit@v4
              with:
                  message: 'Built pdfs'
                  add: '*.pdf'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
