name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
              apk add git
              apk add inkscape
              time bash build.sh
      - name: bruh
        run: echo ::set-env name=COMMIT_MSG::"Built pdfs $(git rev-parse --short "$GITHUB_SHA")"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: COMMIT_MSG
          add: '*.pdf'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
